### ISSUE TITLE
Support for MSI GT73VR

### ISSUE THREAD

**Issue by eugaz** [Zibri/MSI-GT7x-VGA-SWITCH#2]
Guessing if this will work with the MSI GT73VR Titan Pro.

**Comment by Zibri** [comment]
for sure but the offset will be different.. don't use it as it is... add me on facebook and we can find it together

**Comment by Zibri** [comment]
http://fb.com/Zibri

**Comment by superbonaci** [comment]
I've sent you a message on fb.

**Comment by eugaz** [comment]
Sent you a message in facebook.

**Comment by Zibri** [comment]
Updated the source of msi_vga with the new offset.
