### ISSUE TITLE
Advise needed

### ISSUE THREAD

**Issue by erkexzcx** [Zibri/MSI-GT7x-VGA-SWITCH#4]
Hi,

Would you don't mind to publicitly share how you managed to extract all this information? Exactly speaking - how did you extract all the data blocks and values needed to switch between Nvidia and Intel?

I assume you did some sort of system HW access recording from Windows and found the difference? The content of C code is dead simple. What is not clear to me is how you extracted all those values.

Thanks!

**Comment by erkexzcx** [comment]
I have `MSI GS66 11UH` laptop and tried using `RW everything` app to find difference in EC controller between boots with nvidia and boots with hybrid graphics. Here are the consistent addresses between using nvidia only and hybrid graphics:
```
Address: 2E with values intel=3B and nvidia=7B
Address: FA with values intel=03 and nvidia=07
```

Changing `FA` value makes screen go dark, while changing `2E` seem to do nothing. Any advise is appreciated.

**Comment by Zibri** [comment]
did you miss that this utility was meant for a different model and it's specific for a bios version ?

**Comment by erkexzcx** [comment]
> did you miss that this utility was meant for a different model and it's specific for a bios version ?

No, I did not. What I requested you is to provide a guidelines how you found all of this. But if you'd like to keep everything to yourself - that's OK.

**Comment by Zibri** [comment]
Oh I didn't get that. How? Easy: I set the cards on and off and checked what changed or stayed the same in the EC.
Then I wrote that small program to just set that byte.
